hydra:
  job_logging:
    formatters:
      simple:
        format: "%(asctime)s - %(levelname)s - %(message)s"

info:
  user: ${oc.env:USER,default_user}

data:
  data_dir: "data"
  dataset_name: "norman"
